### PR TITLE
fixes for compatibility with zig 0.11.0

### PR DESCRIPTION
**Pull request by radarroark**
Not ready to merge. After these changes, the modules can individually build with 0.11.0-dev.3132+465272921 but the testrunner build command fails:

```
$ zig build --build-file test/testrunner/build.zig --prefix ./
zig build-exe testrunner Debug native: error: warning: FileNotFound: test/testrunner/src/main.zig
error: FileNotFound
```

Yours truly looked into it and found that it is a build system bug. Here's the fix: https://github.com/ziglang/zig/pull/15717 Hopefully that can get into the release. Shake and bake!

### CODE REVIEW

**Comment by malcolmstill** [comment]
We'll also need to fix any casts https://github.com/ziglang/zig/pull/16163

**Comment by radarroark** [comment]
All casts should be fixed now. The powers that be think they can stop radar with all these breaking changes, but they only make me stronger...

Ah, but there's one more error in the testrunner. Looks like some kind of workaround but wasn't sure what to do with it:

```
zig-linux-x86_64-0.11.0-dev.3909+9e0ac4449/lib/std/json/static.zig:170:41: error: type '[]const testrunner.Command' has no members
    return ParseFromValueError || Source.NextError || Source.PeekError || Source.AllocError;
                                  ~~~~~~^~~~~~~~~~
zig-linux-x86_64-0.11.0-dev.3909+9e0ac4449/lib/std/json/static.zig:170:41: note: slice values have 'len' and 'ptr' members
src/testrunner.zig:93:28: note: called from here
        _ = json.ParseError([]const Command);
            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
```

**Comment by malcolmstill** [comment]
> All casts should be fixed now. The powers that be think they can stop radar with all these breaking changes, but they only make me stronger...
> 
> Ah, but there's one more error in the testrunner. Looks like some kind of workaround but wasn't sure what to do with it:
> 
> ```
> zig-linux-x86_64-0.11.0-dev.3909+9e0ac4449/lib/std/json/static.zig:170:41: error: type '[]const testrunner.Command' has no members
>     return ParseFromValueError || Source.NextError || Source.PeekError || Source.AllocError;
>                                   ~~~~~~^~~~~~~~~~
> zig-linux-x86_64-0.11.0-dev.3909+9e0ac4449/lib/std/json/static.zig:170:41: note: slice values have 'len' and 'ptr' members
> src/testrunner.zig:93:28: note: called from here
>         _ = json.ParseError([]const Command);
>             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
> ```

It might be with recent changes that those particular `json.ParseError` lines (which you are right were a workaround) aren't required.

However, I'm expecting because of https://github.com/ziglang/zig/pull/15602 and https://github.com/ziglang/zig/pull/15705 that the json parsing stuff will be totally broken anyway.

**Comment by malcolmstill** [comment]
@radarroark just fixed some conflicts on your branch for this change https://github.com/malcolmstill/zware/pull/192. I'm going to see if I can work around the testrunner not building and take a look at it what changes are required for the JSON parser stuff due to https://github.com/ziglang/zig/pull/15602 and https://github.com/ziglang/zig/pull/15705

**Comment by malcolmstill** [comment]
Ah so we can still build `testrunner` (modulo json parser changes) as long as we `cd` to its directory? We can just update the GitHub action to do that and it should be fine for the moment

**Comment by malcolmstill** [comment]
https://github.com/ziglang/zig/pull/15981 may be what we need; trying it out now.

**Review by malcolmstill — APPROVED** [review]

**Comment by malcolmstill** [comment]
Green light means go @radarroark!

**Comment by malcolmstill** [comment]
Thanks for all the help on this @radarroark

**Comment by radarroark** [comment]
You are welcome sir
